import { withLayout } from '@modules/layout/Layout/withLayout';
import { Rating, Tag } from '@modules/ud-ui';
import Head from 'next/head';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Tag color='primary' size='m' href='https://google.com'>
          tag
        </Tag>
        <Rating rating={2} isEditable />
      </main>
    </div>
  );
};

export default withLayout(Home);
